### ISSUE TITLE
Crash when clicking twice after ls

### ISSUE THREAD

**Issue by Lahvuun** [letoram/cat9#1]
https://user-images.githubusercontent.com/6643565/174504074-8878a052-c088-4470-81d8-b21f26901742.mp4

Seems to only happen in directories with lots of files, I used a test folder with 50 empty files.

**Comment by letoram** [comment]
seems to be the tracking between a grid coordinate and whatever job header is at that location, it's somewhat broken after multicolumn layouts started to get added - pushed something that might mask it

**Comment by Lahvuun** [comment]
Looks like 8779e53162b5d393b70871399c65141202aabca4 fixed it. Thank you!
